Repository jzlotek/drexel-cs451, pull requests merged in 2019-07, with the labels that each got.

#7 Serialization
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_annotations_2_9_0.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_core_2_9_8.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_databind_2_9_8.xml
  .idea/modules/checkers.main.iml
  .idea/modules/checkers.test.iml
  build.gradle
  src/main/java/tbc/client/components/Board.java
  src/main/java/tbc/client/components/Piece.java
  src/main/java/tbc/client/scene/GameScene.java
  src/main/java/tbc/util/SerializationUtil.java
  src/main/java/tbc/util/SerializationUtilBoard.java
  src/main/java/tbc/util/SerializationUtilJSON.java
  src/test/java/tbc/util/SerializationUtilBoardTest.java
  src/test/java/tbc/util/SerializationUtilJSONTest.java
Labels: enhancement

#10 Added latex for requirements.
  docs/requirements.tex
Labels: documentation

#11 docs
  docs/requirements.tex
Labels: documentation

#8 V1.1 Lobby Communication with Clients / Game Logic
  .project
  src/main/java/tbc/Constants.java
  src/main/java/tbc/server/Lobby.java
  src/main/java/tbc/server/Player.java
  src/main/java/tbc/server/Server.java
  src/main/java/tbc/util/ConsoleWrapper.java
Labels: enhancement

#14 document update (preet and jake)
  docs/board.png
  docs/cite.bib
  docs/requirements.pdf
  docs/requirements.synctex.gz
  docs/requirements.tex
Labels: documentation

#16 Add design / test case structures
  docs/design/design.synctex.gz
  docs/design/design.tex
  docs/requirements/board.png
  docs/requirements/requirements.pdf
  docs/requirements/requirements.synctex.gz
  docs/requirements/requirements.tex
  docs/test/test.synctex.gz
  docs/test/test.tex
Labels: documentation

#17 Java swing2
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/libraries/Gradle__org_openjfx_javafx_base_11_0_2.xml
  .idea/libraries/Gradle__org_openjfx_javafx_base_win_11_0_2.xml
  .idea/libraries/Gradle__org_openjfx_javafx_controls_11_0_2.xml
  .idea/libraries/Gradle__org_openjfx_javafx_controls_win_11_0_2.xml
  .idea/libraries/Gradle__org_openjfx_javafx_fxml_win_11_0_2.xml
  .idea/libraries/Gradle__org_openjfx_javafx_graphics_11_0_2.xml
  .idea/libraries/Gradle__org_openjfx_javafx_graphics_win_11_0_2.xml
  .idea/markdown-navigator.xml
  .idea/markdown-navigator/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/checkers.iml
  .idea/modules/checkers_main.iml
  .idea/modules/checkers_test.iml
  .idea/vcs.xml
  .idea/workspace.xml
  .project
  build.gradle
  src/main/java/tbc/client/Main.java
  src/main/java/tbc/client/components/Board.java
  src/main/java/tbc/client/components/Drawable.java
  src/main/java/tbc/client/components/GameScene.java
  src/main/java/tbc/client/components/Piece.java
  src/main/java/tbc/client/components/Player.java
  src/main/java/tbc/client/scene/GameScene.java
  src/main/java/tbc/util/SocketUtil.java
Labels: enhancement

#19 Client server integration :3
  .idea/$PRODUCT_WORKSPACE_FILE$
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_annotations_2_9_0.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_core_2_9_8.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_databind_2_9_8.xml
  .idea/libraries/Gradle__javax_annotation_javax_annotation_api_1_2.xml
  .idea/libraries/Gradle__javax_validation_validation_api_1_1_0_Final.xml
  .idea/libraries/Gradle__javax_ws_rs_javax_ws_rs_api_2_1.xml
  .idea/libraries/Gradle__javax_ws_rs_jsr311_api_1_1_1.xml
  .idea/libraries/Gradle__junit_junit_4_12.xml
  .idea/libraries/Gradle__org_apiguardian_apiguardian_api_1_1_0.xml
  .idea/libraries/Gradle__org_glassfish_grizzly_grizzly_framework_2_4_0.xml
  .idea/libraries/Gradle__org_glassfish_grizzly_grizzly_http_2_4_0.xml
  .idea/libraries/Gradle__org_glassfish_grizzly_grizzly_http_server_2_4_0.xml
  .idea/libraries/Gradle__org_glassfish_hk2_external_javax_inject_2_5_0_b42.xml
  .idea/libraries/Gradle__org_glassfish_hk2_osgi_resource_locator_1_0_1.xml
  .idea/libraries/Gradle__org_glassfish_jersey_containers_jersey_container_grizzly2_http_2_26.xml
  .idea/libraries/Gradle__org_glassfish_jersey_core_jersey_client_2_26.xml
  .idea/libraries/Gradle__org_glassfish_jersey_core_jersey_common_2_26.xml
  .idea/libraries/Gradle__org_glassfish_jersey_core_jersey_server_2_26.xml
  .idea/libraries/Gradle__org_glassfish_jersey_media_jersey_media_jaxb_2_26.xml
  .idea/libraries/Gradle__org_hamcrest_hamcrest_core_1_3.xml
  .idea/libraries/Gradle__org_junit_platform_junit_platform_commons_1_5_0.xml
  .idea/libraries/Gradle__org_junit_platform_junit_platform_engine_1_5_0.xml
  .idea/libraries/Gradle__org_junit_vintage_junit_vintage_engine_5_5_0.xml
  .idea/libraries/Gradle__org_opentest4j_opentest4j_1_2_0.xml
  .idea/markdown-exported-files.xml
  .idea/markdown-navigator.xml
  .idea/markdown-navigator/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/checkers.iml
  .idea/modules/checkers.main.iml
  .idea/modules/checkers.test.iml
  .idea/vcs.xml
  .idea/workspace.xml
  build.gradle
  src/main/java/tbc/client/Main.java
  src/main/java/tbc/client/components/ComponentStore.java
  src/main/java/tbc/client/components/GameScene.java
  src/main/java/tbc/server/Lobby.java
  src/main/java/tbc/server/Server.java
  src/main/java/tbc/shared/GameState.java
  src/main/java/tbc/shared/Move.java
Labels: enhancement, help wanted

#20 Test Cases (Vector, GameState, Serializer)
  src/main/java/tbc/client/checkers/Board.java
  src/main/java/tbc/client/checkers/Space.java
  src/main/java/tbc/client/checkers/Vector.java
  src/main/java/tbc/client/components/Board.java
  src/main/java/tbc/client/components/Drawable.java
  src/main/java/tbc/client/components/Piece.java
  src/main/java/tbc/shared/GameState.java
  src/main/java/tbc/util/SerializationUtilBoard.java
  src/test/java/tbc/client/checkers/SpaceTest.java
  src/test/java/tbc/client/checkers/VectorTest.java
  src/test/java/tbc/client/components/ComponentStoreTest.java
  src/test/java/tbc/shared/GameStateTest.java
  src/test/java/tbc/util/SerializationUtilBoardTest.java
  src/test/java/tbc/util/SerializationUtilJSONTest.java
  src/test/java/tbc/util/SocketUtilTest.java
Labels: tests

#21 Design document
  docs/design/design.pdf
  docs/design/design.synctex.gz
  docs/design/design.tex
  docs/design/img/CS 451 Checkers Flowchart.png
  docs/design/img/Gameplay Architecture.png
  docs/design/img/Menu Logic.png
  docs/design/img/Network Architecture.png
  docs/design/img/board dark.png
  docs/design/img/board.png
  docs/design/img/boardManager.PNG
  docs/design/img/checkers complete design UML.png
  docs/design/img/checkersPiece black crowned.png
  docs/design/img/checkersPiece black.png
  docs/design/img/checkersPiece red crowned.png
  docs/design/img/checkersPiece red.png
  docs/design/img/gameManager.png
  docs/design/img/mockup ingame.png
  docs/design/img/mockup loss.png
  docs/design/img/mockup serverlist.png
  docs/design/img/mockup victory.png
  docs/design/img/moveManager.PNG
  docs/design/img/pieceManager.PNG
  docs/design/img/snippedUML.png
Labels: documentation
